config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'admin/index',as: 'admin'
  get 'admin/users',as: 'users_list'
  get 'home/another'
  get 'about/index', as: 'about_us'
  get 'contact/index', as: 'contact_us'
  get 'home/search'
  get '/users' => 'registrations#index'
  get 'house/:id/booking/booked' => 'houses#house_booking',as:'after_house_booking'
  get 'houses/:id/booked/:booked_status' => 'houses#booked',as: 'booked'
  post 'house/:id/booking/booked' => 'houses#house_booking',as: 'client_house_booking'
  
  delete 'delete/users/:id' => 'admin#destroy_user',as: 'delete_user'
  
  devise_for :users, controllers: { registrations: "registrations" }
  resources :houses do
    resources :house_pictures, shallow: true
      collection do
        post :confirm 
      end
    
      member do
        get 'booking'
      end
  end
  
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
# frozen_string_literal: true
# HousesController 

class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy booking house_booking]
  before_action :set_owner, only: %i[booking show house_booking]
  before_action :authenticate_user!, except: %i[show booking]

  def index
    @owner = User.find_by(id: current_user.id)
    @houses = House.all
                   .where(user_id: current_user.id)
                   .order('created_at desc')
                   .page(params[:page])
                   .per(4)
    @charges = Charge.find_by(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json { render json: @houses }
    end
  end

  def booked
    @booked = House.all
                   .where(user_id: current_user.id, booked_status: params[:booked_status])
                   .order('created_at desc')
                   .page(params[:page])
                   .per(4)
  end

  def show
    @photos = HousePicture.all.where(house_id: @house.id)
  end

  def booking
    @photos = HousePicture.all.where(house_id: @house.id)
  end

  def house_booking
    @photos = HousePicture.all.where(house_id: @house.id)
    if current_user.user_category == 'Renter'
      @house.booked_status = 'booked'
      respond_to do |format|
        if @house.update(booked_status: @house.booked_status)
          BookingMailer.booking_mail_renter(current_user, @owner, @house)
                       .deliver_later
          BookingMailer.booking_mail_owner(current_user, @owner, @house)
                       .deliver_later
          format.html { redirect_to root_path, notice: 'House is booked successfully!!!' }
          format.json { head :no_content }
        else
          format.html { render action: 'booking' }
          format.json { render json: @house.errors, status: :unprocessable_entity }
        end
      end
    else
        redirect_to root_path,
          notice: 'You must have a renter account please create it first.'
    end
  end

  def new
    if params[:back]
      @house = House.new(house_params)
    else
      @house = House.new
    end
  end

  def confirm
    @house = House.new(house_params)
    render new_house_path if @house.invalid?
  end

  def edit; end

  def create
    @user = User.find_by(id: current_user.id)
    @house = House.new(house_params)
    @house.booked_status = 'not booked'
    respond_to do |format|
      if @house.save
        HouseMailer.house_mail(@user, @house).deliver_later
        format.html {
          redirect_to @house, notice: 'House was successfully created.'
        }
        format.json {
          render json: @house, status: :created, location: @house
        }
      else
        format.html {
          render action: 'new'
        }
        format.json {
          render json: @house.errors, status: :unprocessable_entity
        }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html {
          redirect_to @house, notice: 'house was successfully updated.'
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json {
          render json: @house.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  private

  def house_params
    params.require(:house)
          .permit(:location, :number_of_rooms, :booked_status, :description)
          .merge(user: current_user)
  end

  def set_house
    @house = House.find(params[:id])
  end
  
  def set_owner
    @owner = User.find_by(id: @house.user_id)
  end
end

app/helpers/houses_helper.rb
module HousesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_houses_path
        elsif action_name == 'edit'
          house_path
        end
    end
end

app/views/houses/_form.html.erb
<%= form_with(model: @house,local: true,url: choose_new_or_edit) do |f|%>
    <% if @house.errors.any? %>
        <div class="error_explanation">
            <h2><%= @house.errors.count%> errors occured!!</h2>
            <ul>
                <% @house.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end%>
    <br>

  <div class="field form-group row">
    <%= f.label:location, class: 'col-sm-2 control-label', style:'text-align:right;margin-top:7px' %>
    <div class="col-sm-10">
      <%= f.text_field:location, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group row">
    <%= f.label:number_of_rooms, class: 'col-sm-2 control-label', style:'text-align:right;margin-top:7px' %>
    <div class="col-sm-10">
      <%= f.text_field:number_of_rooms, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group row">
    <%= f.label:description, class: 'col-sm-2 control-label', style:'text-align:right;margin-top:7px' %>
    <div class="col-sm-10">
      <%= f.hidden_field:description, id: :desc %>
      <trix-editor input="desc"></trix-editor>
      
    </div>
  </div>
  
  <div class="field row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
         <%= f.submit 'Save', class: 'btn btn-primary btn-save', style:'width:100%'%>
    </div>
  </div>
<% end %>

app/views/houses/_payment.html.erb
<!--<% if !@house.persisted? %>-->
    
<!--    <div class="field row">-->
<!--        <div class="col-sm-1"></div>-->
<!--        <div class="col-sm-10">-->
<!--            <h6>Payment</h6>-->
<!--            <div class="pay_msg">-->
<!--                <span class="glyphicon glyphicon-credit-card"></span>-->
<!--                House posting cost only <strong>$5</strong> so make it worth.-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="form-row row">-->
<!--        <div class="col-sm-1"></div>-->
<!--        <div class="col-sm-10">-->
<!--            <label for="card-element">-->
<!--              Credit or debit card-->
<!--            </label>-->
<!--        </div>-->
<!--        <div style="float:left;visibility: hidden;">d</div>-->
<!--        <div class="col-sm-1"></div>-->
<!--        <div class="col-sm-10">-->
<!--            <div id="card-element">-->
              <!-- A Stripe Element will be inserted here. -->
<!--            </div>-->
<!--        </div>-->
        <!-- Used to display form errors. -->
<!--        <div class="col-sm-1"></div>-->
<!--        <div class="col-sm-10">-->
<!--            <div id="card-errors" role="alert"></div>-->
<!--        </div>-->
<!--      </div>-->
      
<!--      <% if @charges.present? %>-->
<!--       <div class="field row">-->
<!--            <div class="col-sm-1"></div>-->
<!--            <div class="col-sm-10">-->
<!--              <h6>Previously used cards</h6>-->
<!--              <table class="table table-responsive table-bordered">-->
<!--                  <thead>-->
<!--                      <th>Card Brand</th>-->
<!--                      <th>Last 4 Digits</th>-->
<!--                      <th>Expiration Month</th>-->
<!--                      <th>Expiration Year</th>-->
<!--                  </thead>-->
<!--                  <tr><%= current_user.charges.card_brand%></tr>-->
<!--                  <tr><%= current_user.charges.card_last4%></tr>-->
<!--                  <tr><%= current_user.charges.card_exp_month%></tr>-->
<!--                  <tr><%= current_user.charges.card_exp_year%></tr>-->
<!--              </table>-->
<!--            </div>-->
<!--        </div>     -->
<!--      <% end %>-->
<!--<% end %>-->

app/views/houses/booked.html.erb
<% if @booked.present? %>
  <h3 style="float:left;margin-top:8px;margin-left:10px">These house owned by <b><%= current_user.names%> and <%= params[:booked_status]%></b></h3>
<% else %>
 <% if params[:booked_status]=='booked' %>
     <h3 style="float:left;margin-top:8px;margin-left:10px">None of your houses is booked</b></h3>
 <% else %>
  <h3 style="float:left;margin-top:8px;margin-left:10px">All of your house has been booked</b></h3>
 <% end %>
<% end %>

 <%= link_to new_house_path,style:'text-align:right;margin-top:10px',class:'btn btn-success float-right col-xs-12' do %>
    <i class="glyphicon glyphicon-plus"></i>New House
  <% end %>
  <div class="clearfix"></div>
  <div class="row">
    <% @booked.each do |booked| %>
      
        <div class="col col-6 col-md-6 col-sm-12 col-xs-12">
          <div style="background-color:#FFFFFF;margin:10px;padding:10px">
          <h5>This house has <b><%= booked.number_of_rooms %></b> rooms and located in <b><%= booked.location %> (<label style="color:#0c6bd1"><%=booked.booked_status%></label>)</b>.</h5>
          <label style="font-size:10px"></label>
          <p>
            <%= sanitize booked.description.truncate(200, omission: '... (continued)') %>
          </p>
          <%= link_to new_house_house_picture_path(booked.id),class:'btn btn-info btn-sm' ,style:'width:180px;float:left' do%>
            <div style="float:left"><i class="glyphicon glyphicon-plus"></i></div>Add house pictures
          <% end %>
          <%= link_to  booked,class:'btn btn-info btn-sm' ,style:'margin-left:20px;width:80px' do %>
            <div style="padding-top:3px;float:left"><i class="glyphicon glyphicon-eye-open"></i></div>View
          <% end %>
          <%= link_to  edit_house_path(booked) ,class:'btn btn-info btn-sm' ,style:'margin-left:20px;width:80px;float:left' do%>
            <div style="float:left"><i class="glyphicon glyphicon-pencil"></i></div>Edit
          <% end %>
          
          <%= link_to  house_path(booked.id),method: :delete,data:{confirm:'are you sure you want to delete?'},class:'btn btn-danger btn-sm',style:'margin-left:20px;width:100px' do%>
                <div style="padding-top:3px;float:left"><i class="glyphicon glyphicon-trash"></i></div>Delete
          <% end %>
         </div>  
        </div>
      
      <p>
       
     
    <% end %>
    </div>
  <div class="container pagination justify-content-center">
     <%= paginate @booked , theme: 'twitter-bootstrap-4'%>
  </div>
<br>

app/views/houses/booking.html.erb
<p>
  <h2>Full information on this house</h2>
  <p>This house has <b><%= @house.number_of_rooms %></b> rooms and located in <b><%=@house.location%></b>.</p>
</p>
<br>
<p>
  <%= sanitize @house.description %>
</p>
<h3>Photos</h3>
<div class="row">
    <% @photos.each do |photo|%>
    <div class="col col-3">
        <%=image_tag(photo.image_url(:thumb),style:'width:100%;height:200px;margin-bottom:20px')%>
    </div>
    <% end %>
    
</div>
<%= link_to 'Book Now',client_house_booking_path(@house.id) ,class:'btn btn-info' ,style:'width:200px' %>
 <br><br>
<h2>House owner's addresses</h2>
<div style="width:370px"><hr/></div>
<label>Names:        <b><%= @owner.names %></b></label><br>
<label>Email:        <b><%= @owner.email%></b></label><br>
<label>Phone Number: <b><%= @owner.phone_number%></b></label><br>

app/views/houses/confirm.html.erb
<br>
<div class="field row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <h5 style="text-align:center">Please confirm to get your house posted</h5><br>
    </div>
</div>
      <%= form_with(model: @house, url: @house, local: true,id:'new_house') do |form| %>
        <div class="field row">
          <div class="col-sm-1"></div>
          <div class="col-sm-10">
            <%= form.hidden_field :location %>
            <%= form.hidden_field :number_of_rooms %>
            <%= form.hidden_field :description %>
            
            <p>Location: <%= @house.location %></p>
            <p>Rooms Number: <%= @house.number_of_rooms %></p>
            <p>Description: <%= sanitize @house.description %></p>
            <hr/>
          </div>
        </div>
        <div>
          <!--<%= render 'payment' %>-->
        </div><br>
        <div class="field row" style="float:left;margin-left: 55px;">
          <div class="col-sm-1"></div>
          <div class="col-sm-4">
            <%= form.submit  "Confirm",class:'btn btn-success',style:'float:left;width:300px'%>
          </div>
        </div>
      <% end %>
      
      <%= form_with(model: @house, url: new_house_path, local: true, method: 'get') do |form| %>
          <%= form.hidden_field :location %>
          <%= form.hidden_field :number_of_rooms %>
          <%= form.hidden_field :description %>
          <%= form.submit "Back", name: 'back',class:'btn btn-info',style:'margin-left:20px;width:300px;margin-right: 100px;float:right' %>
      <% end %>


<!--<script type="text/javascript">-->
<!--$(document).on('turbolinks:load', function(){-->
<!--    const public_key=document.querySelector('meta[name="stripe-public-key"]').content;-->
<!--    const stripe = Stripe(public_key);-->
<!--    const elements=stripe.elements();-->
<!--    const style={-->
<!--        base: {-->
<!--        color: '#32325d',-->
<!--        lineHeight: '18px',-->
<!--        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',-->
<!--        fontSmoothing: 'antialiased',-->
<!--        fontSize: '16px',-->
<!--        '::placeholder': {-->
<!--          color: '#aab7c4'-->
<!--        }-->
<!--      },-->
<!--      invalid: {-->
<!--        color: '#fa755a',-->
<!--        iconColor: '#fa755a'-->
<!--      }-->
<!--    };-->
    
<!--    const card=elements.create('card',{style: style});-->
<!--    card.mount("#card-element");-->
<!--    card.addEventListener('change',({errors})=>{-->
<!--        const displayError=document.getElementById('card-errors');-->
<!--        if(errors){-->
<!--            displayError.textContent=errors.message;-->
<!--        }-->
<!--        else{-->
<!--            displayError.textContent="";-->
<!--        }-->
<!--    });-->
    
<!--    const form=document.getElementById('new_house');-->
<!--    form.addEventListener('submit',async(event)=>{-->
<!--        event.preventDefault();-->
<!--        const {token,error} = await stripe.createToken(card);-->
<!--        if(event.error){-->
<!--            const errorElement=document.getElementById('card-errors');-->
<!--            errorElement.textContent=event.error.message;-->
<!--        }else{-->
<!--            stripeTokenHandler(token);-->
<!--        }-->
<!--    });-->
    
<!--    const stripeTokenHandler = (token) =>{-->
<!--        const form=document.getElementById('new_house');-->
<!--        const hiddenInput=document.createElement('input');-->
<!--        hiddenInput.setAttribute('type','hidden');-->
<!--        hiddenInput.setAttribute('name','stripeToken');-->
<!--        hiddenInput.setAttribute('value',token.id);-->
<!--        form.appendChild(hiddenInput);-->
<!--        ["brand","exp_month","exp_year","last4"].forEach(function(field){-->
<!--            addFieldToForm(form,token,field)-->
<!--        });-->
        
<!--        form.submit();-->
<!--    }-->
<!--    function addFieldToForm(form,token,field){-->
<!--        const hiddenInput=document.createElement('input');-->
<!--        hiddenInput.setAttribute("type","hidden");-->
<!--        hiddenInput.setAttribute("name","charge[card_"+field+"]");-->
<!--        hiddenInput.setAttribute("value",token.card[field]);-->
<!--        form.appendChild(hiddenInput);-->
<!--    }-->
<!--});-->
<!--</script>-->

app/views/houses/edit.html.erb
<h2 style="text-align:center">Update  house</h2><br>
<%= render 'form' %>

app/views/houses/house_booking.html.erb
success

app/views/houses/index.html.erb
 <h1 style="float:left">These house owned by <b><%= @owner.names%></b></h1>
 <%= link_to new_house_path,style:'text-align:right;margin-top:10px',class:'btn btn-success float-right' do %>
    <i class="glyphicon glyphicon-plus"></i>New House
  <% end %>
  <div class="clearfix"></div>
  <div class="row">
    <% @houses.each do |house| %>
      
        <div class="col col-6 col-md-6 col-sm-12">
          <div style="background-color:#FFFFFF;margin:10px;padding:10px">
          <h5>This house has <b><%= house.number_of_rooms %></b> rooms and located in <b><%= house.location %> (<label style="color:#0c6bd1"><%=house.booked_status%></label>)</b>.</h5>
          <label style="font-size:10px"></label>
          <p>
            <%= sanitize house.description.truncate(200, omission: '... (continued)') %>
          </p>
          <%= link_to house_house_pictures_path(house.id),class:'btn btn-info btn-sm' ,style:'width:180px;float:left' do%>
            <div style="float:left"><i class="glyphicon glyphicon-list"></i></div>Add house pictures
          <% end %>
          <%= link_to  house,class:'btn btn-info btn-sm' ,style:'margin-left:20px;width:80px' do %>
            <div style="padding-top:3px;float:left"><i class="glyphicon glyphicon-eye-open"></i></div>View
          <% end %>
          <%= link_to  edit_house_path(house) ,class:'btn btn-info btn-sm' ,style:'margin-left:20px;width:80px;float:left' do%>
            <div style="float:left"><i class="glyphicon glyphicon-pencil"></i></div>Edit
          <% end %>
          
          <%= link_to  house_path(house.id),method: :delete,data:{confirm:'are you sure you want to delete?'},class:'btn btn-danger btn-sm',style:'margin-left:20px;width:100px' do%>
                <div style="padding-top:3px;float:left"><i class="glyphicon glyphicon-trash"></i></div>Delete
          <% end %>
         </div>  
        </div>
      
      <p>
       
     
    <% end %>
    </div>
  <div class="container pagination justify-content-center">
     <%= paginate @houses , theme: 'twitter-bootstrap-4'%>
  </div>
<br>

app/views/houses/new.html.erb
<h5 style="text-align:center">Create a new  house</h5>
<%= render 'form' %>

app/views/houses/show.html.erb
<h5>Please make sure you add at least one house image to get shown to the clients</h5>
<p>
  <h3>This house owned by <b><%= @owner.names%></b></h3><br>
  <p>This house has <%= @house.number_of_rooms %> rooms.</p>
</p>
<br>
<p>
  <%= sanitize @house.description %>
</p>
<br>
<div class="row">
    <% @photos.each do |photo|%>
      <div class="col col-3">
          <%=image_tag(photo.image_url(:thumb),style:'width:100%;height:200px;margin-bottom:20px')%>
      </div>
    <% end %>
</div>
<%= link_to house_house_pictures_path(@house.id),class:'btn btn-info' ,style:'width:200px;float:left' do%>
  <div style="float:left"><i class="glyphicon glyphicon-list"></i></div>View house picture
<% end %>
<%= link_to  edit_house_path(@house) ,class:'btn btn-info' ,style:'margin-left:20px;width:100px;float:left' do%>
  <div style="float:left"><i class="glyphicon glyphicon-pencil"></i></div>Edit
<% end %>
<%= link_to  houses_path,class:'btn btn-success' ,style:'margin-left:20px;width:100px' do %>
  <div style="padding-top:3px;float:left"><i class="glyphicon glyphicon-list"></i></div>Houses
<% end %>