config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'admin/index',as: 'admin'
  get 'admin/users',as: 'users_list'
  get 'home/another'
  get 'about/index', as: 'about_us'
  get 'contact/index', as: 'contact_us'
  get 'home/search'
  get '/users' => 'registrations#index'
  get 'house/:id/booking/booked' => 'houses#house_booking',as:'after_house_booking'
  get 'houses/:id/booked/:booked_status' => 'houses#booked',as: 'booked'
  post 'house/:id/booking/booked' => 'houses#house_booking',as: 'client_house_booking'
  
  delete 'delete/users/:id' => 'admin#destroy_user',as: 'delete_user'
  
  devise_for :users, controllers: { registrations: "registrations" }
  resources :houses do
    resources :house_pictures, shallow: true
      collection do
        post :confirm 
      end
    
      member do
        get 'booking'
      end
  end
  
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<h3 style="text-align:center"> List of houses</h3>

<!--<p><%= notice %></p>-->
<div class="myTable">
<table class="table table-bordered table-hover table-sm">
    <thead class="bg-light">
          <tr>
            <th>ID</th>
            <th>House owner</th>
            <th>Location</th>
            <th>Rooms</th>
            <th>Description</th>
            <th colspan="3" style="text-align:center">Details</th>
          </tr>
    </thead>
    <tbody>
<%@houses.each do |house|%>
    <tr>
        <td><%= house.id%></td>
        <% @user=User.find_by(id: house.user_id)%>
        <td><%= @user.names%></td>
        <td><%= house.location%></td>
        <td><%= house.number_of_rooms%></td>
        <td><%= sanitize house.description.truncate(70, omission: '... (continued)') %></td>
        <td style="text-align:center">
            <%= link_to  house,class:'btn btn-info btn-sm' do %>
              <i class="glyphicon glyphicon-eye-open"></i>
            <% end %>
        </td>
        <td style="text-align:center">
            <%= link_to  edit_house_path(house) ,class:'btn btn-info btn-sm' do%>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
        </td>
        <td style="text-align:center">
          <%= link_to  house_path(house.id),method: :delete,data:{confirm:'are you sure you want to delete?'},class:'btn btn-danger btn-sm' do%>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
    </tr>
    
   
<% end %>
</tbody>
</table>
<div class="container pagination justify-content-center">
              <%= paginate @houses , theme: 'twitter-bootstrap-4'%>
            </div>
</div>

app/views/admin/users.html.erb
<h3 style="text-align:center"> List of Users</h3>

<!--<p><%= notice %></p>-->
<div class="myTable">
<table class="table table-bordered table-hover table-sm">
    <thead class="bg-light">
          <tr>
            <th>ID</th>
            <th>Names</th>
            <th>Email</th>
            <th>Category</th>
            <th>Phone number</th>
            <th>Number of house(s)</th>
            <th colspan="3" style="text-align:center">Details</th>
          </tr>
    </thead>
    <tbody>
<%@users.each do |user|%>
    <tr>
        <td><%= user.id%></td>
        <td><%= user.names%></td>
        <td><%= user.email%></td>
        <td><%= user.user_category%></td>
        <td><%= user.phone_number %></td>
        <% @house_number=user.houses%>
        <% if @house_number.present?%>
          <td><%=@house_number.count%></td>
        <% else %>
          <td>-</td>
        <% end %>
        <td style="text-align:center">
            <%= link_to houses_path, class:'btn btn-info btn-sm' do %>
              <i class="glyphicon glyphicon-list"></i> Houses
            <% end %>
        </td>
        <!--<td style="text-align:center">-->
        <!--    <%= link_to  edit_user_registration_path ,class:'btn btn-info btn-sm' do%>-->
        <!--      <i class="glyphicon glyphicon-pencil"></i>-->
        <!--    <% end %>-->
        <!--</td>-->
        <td style="text-align:center">
          <%= link_to  delete_user_path(user.id),method: :delete,data:{confirm:'are you sure you want to delete?'},class:'btn btn-danger btn-sm' do%>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
    </tr>
    
   
<% end %>
</tbody>
</table>
<div class="container pagination justify-content-center">
              <%= paginate @users , theme: 'twitter-bootstrap-4'%>
            </div>
</div>