config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'admin/index',as: 'admin'
  get 'admin/users',as: 'users_list'
  get 'home/another'
  get 'about/index', as: 'about_us'
  get 'contact/index', as: 'contact_us'
  get 'home/search'
  get '/users' => 'registrations#index'
  get 'house/:id/booking/booked' => 'houses#house_booking',as:'after_house_booking'
  get 'houses/:id/booked/:booked_status' => 'houses#booked',as: 'booked'
  post 'house/:id/booking/booked' => 'houses#house_booking',as: 'client_house_booking'
  
  delete 'delete/users/:id' => 'admin#destroy_user',as: 'delete_user'
  
  devise_for :users, controllers: { registrations: "registrations" }
  resources :houses do
    resources :house_pictures, shallow: true
      collection do
        post :confirm 
      end
    
      member do
        get 'booking'
      end
  end
  
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
# frozen_string_literal: true
# ApplicationController

class ApplicationController < ActionController::Base
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected

  def configure_devise_permitted_parameters
    permitted_params = %i[email password password_confirmation names phone_number user_category]
    if params[:action] == 'update'
      devise_parameter_sanitizer.permit(:account_update, keys: [permitted_params, :current_password])
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.permit(:sign_up, keys: [permitted_params])
    end
  end

  def after_sign_in_path_for(*)
    @user = User.find_by(email: current_user.email)
    if @user.user_category == 'Renter'
      if params[:id].present?
        house_booking_path(params[:id])
      else
        root_path
      end
    else
      houses_path
    end
  end
end

app/views/application/_flash_errors.html.erb
<% flash.each do |key, value| %>
          <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top:10px">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= value %>
          </div>
        <% end %>

app/views/application/_footer.html.erb
<div class="container-fluid">
        <footer class="text-white mt-4" style="margin-top:50px;position:fixed;background-color: #343a40;width: 100% ;height: 60px ;bottom: 0 ;text-align: center; padding: 19px">
          <label>© 2018 Copyright house rent.</label>
        </footer>
    </div>

app/views/application/_html_head.html.erb
<title>HouseRentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<%= javascript_include_tag 'application','https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.css" rel="stylesheet"/>
    <!--<%= tag :meta, name: "stripe-public-key", content: Figaro.env.stripe_publishable_key %>-->

app/views/application/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-expand-md navbar-light bg-light">
  <div class="container">
   <%=link_to image_tag("logo.PNG",height:'40px'), root_path,class:'navbar-brand'%>
     
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=link_to "Home",root_path,class:'home nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to "About Us", about_us_path ,class:'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to "Contact Us", contact_us_path ,class:'nav-link'%>
      </li>
      <% if current_user.present? && current_user.user_category=="House Owner"%>
        <li class="nav-item">
          <%= link_to "All your houses", houses_path ,class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Booked houses", booked_path(current_user.id,'booked') ,class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Not booked houses", booked_path(current_user.id,'not booked') ,class:'nav-link'%>
        </li>
      <% end %>
       <% if current_user.present? && current_user.admin == true %>
         <li class="nav-item">
            <%= link_to "Houses", admin_path ,class:'nav-link'%>
         </li>
         <li class="nav-item">
            <%= link_to "Manage Users", users_list_path ,class:'nav-link'%>
         </li>
       <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item">
        
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Welcome <%= current_user.names.capitalize %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbardrop">
          <%= link_to "Edit", edit_user_registration_path,class:'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign out", destroy_user_session_path,class:'dropdown-item', method: :delete %>
        </div>
      </li>
       <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path,class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign in", new_user_session_path,class:'nav-link' %>
      </li>
       <% end %>
    </ul>
  </div>
  </div>
</nav>